version: '3.4'

services:
  movies-api:
    image: ${DOCKER_REGISTRY-}moviesapi
    build:
      context: .
      dockerfile: Movies-API/Dockerfile
    ports:
      - "63575:80"
  ms-sql-server:
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "yourStrong(!)Password"
    ports:
      - "1433:1433"
  front:
    image: nadahkhaledd/movies_reviews_new
    ports:
      - "8080:4040"